//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int OrderId { get; set; }
        public string PizzaName { get; set; }
        public string Address { get; set; }
        public string CreditcardNo { get; set; }
        public string size { get; set; }
        public string crust { get; set; }
        public string Toppings { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
